<?php
// Post class definition
class Post
{
    public $id;
    public $title;
    public $comments = [];

    public function __construct($id, $title)
    {
        $this->id = $id;
        $this->title = $title;
    }

    public function addComment($comment)
    {
        $this->comments[] = $comment;
    }

    public function displayPost()
    {
        echo "<li><strong>" . $this->title . "</strong>";
        if (!empty($this->comments)) {
            echo "<ul>";
            foreach ($this->comments as $comment) {
                echo "<li>" . $comment->text . "</li>"; // Accessing text property directly
            }
            echo "</ul>";
        }
        echo "</li>";
    }
}

// Comment class definition
class Comment
{
    public $text;

    public function __construct($text)
    {
        $this->text = $text;
    }

    public function __toString()
    {
        return $this->text; // Implement string conversion
    }
}

// Database connection and query
$servername = "localhost";
$username = "RalfsEgle";
$password = "password";
$dbname = "php27032025";

$conn = new mysqli($servername, $username, $password, $dbname);

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$sql = "SELECT post.id AS post_id, post.title AS post_title, comments.content
        FROM post
        LEFT JOIN comments ON post.id = comments.post_id
        ORDER BY post.id, comments.comment_id";

$result = $conn->query($sql);

if ($result->num_rows > 0) {
    $posts = [];
    while ($row = $result->fetch_assoc()) {
        if (!isset($posts[$row['post_id']])) {
            $posts[$row['post_id']] = new Post($row['post_id'], $row['post_title']);
        }
        if ($row['content'] !== null) { // Only add comment if content exists
            $comment = new Comment($row['content']);
            $posts[$row['post_id']]->addComment($comment);
        }
    }

    echo "<ul>";
    foreach ($posts as $post) {
        $post->displayPost();
    }
    echo "</ul>";
} else {
    echo "No data found.";
}

$conn->close();
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Posts with Comments</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            padding: 20px;
        }

        ul {
            list-style-type: none;
            padding-left: 20px;
        }

        li {
            margin-bottom: 10px;
        }

        strong {
            color: #333;
        }
    </style>
</head>

<body>
    <!-- Content will be generated by PHP -->
</body>

</html>